import type { InstrumentRecord } from "@/modules/dashboard/instrument-catalog";

/**
 * Curated v1 seed of liquid US equities and ETFs for Watchlist search.
 * Not a full market universe — enough for Pre-Trade Research workflows.
 */
export const SEED_US_INSTRUMENTS: InstrumentRecord[] = [
  { ticker: "AAPL", name: "Apple Inc.", kind: "equity" },
  { ticker: "MSFT", name: "Microsoft Corporation", kind: "equity" },
  { ticker: "NVDA", name: "NVIDIA Corporation", kind: "equity" },
  { ticker: "GOOGL", name: "Alphabet Inc. Class A", kind: "equity" },
  { ticker: "AMZN", name: "Amazon.com, Inc.", kind: "equity" },
  { ticker: "META", name: "Meta Platforms, Inc.", kind: "equity" },
  { ticker: "TSLA", name: "Tesla, Inc.", kind: "equity" },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc. Class B", kind: "equity" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", kind: "equity" },
  { ticker: "V", name: "Visa Inc.", kind: "equity" },
  { ticker: "UNH", name: "UnitedHealth Group Incorporated", kind: "equity" },
  { ticker: "XOM", name: "Exxon Mobil Corporation", kind: "equity" },
  { ticker: "JNJ", name: "Johnson & Johnson", kind: "equity" },
  { ticker: "WMT", name: "Walmart Inc.", kind: "equity" },
  { ticker: "MA", name: "Mastercard Incorporated", kind: "equity" },
  { ticker: "PG", name: "The Procter & Gamble Company", kind: "equity" },
  { ticker: "HD", name: "The Home Depot, Inc.", kind: "equity" },
  { ticker: "CVX", name: "Chevron Corporation", kind: "equity" },
  { ticker: "MRK", name: "Merck & Co., Inc.", kind: "equity" },
  { ticker: "ABBV", name: "AbbVie Inc.", kind: "equity" },
  { ticker: "PEP", name: "PepsiCo, Inc.", kind: "equity" },
  { ticker: "KO", name: "The Coca-Cola Company", kind: "equity" },
  { ticker: "AVGO", name: "Broadcom Inc.", kind: "equity" },
  { ticker: "COST", name: "Costco Wholesale Corporation", kind: "equity" },
  { ticker: "AMD", name: "Advanced Micro Devices, Inc.", kind: "equity" },
  { ticker: "NFLX", name: "Netflix, Inc.", kind: "equity" },
  { ticker: "CRM", name: "Salesforce, Inc.", kind: "equity" },
  { ticker: "ADBE", name: "Adobe Inc.", kind: "equity" },
  { ticker: "INTC", name: "Intel Corporation", kind: "equity" },
  { ticker: "CSCO", name: "Cisco Systems, Inc.", kind: "equity" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", kind: "etf" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", kind: "etf" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", kind: "etf" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF", kind: "etf" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", kind: "etf" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", kind: "etf" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", kind: "etf" },
  { ticker: "ARKK", name: "ARK Innovation ETF", kind: "etf" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", kind: "etf" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", kind: "etf" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", kind: "etf" },
  { ticker: "GLD", name: "SPDR Gold Shares", kind: "etf" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", kind: "etf" },
  { ticker: "HYG", name: "iShares iBoxx $ High Yield Corporate Bond ETF", kind: "etf" },
];
